<?php
require "auth.php";require_admin();$page_title="Dashboard Admin";
if(isset($_POST["add_menu"])){ $nama=trim($_POST["nama"]);$harga=(int)$_POST["harga"];$kat=trim($_POST["kategori"]);$gambar="assets/poster.jpg";$st=$conn->prepare("INSERT INTO menu(nama,harga,kategori,gambar,status) VALUES(?,?,?,?,1)");$st->bind_param("siss",$nama,$harga,$kat,$gambar);$st->execute();header("Location: admin.php?ok=menu");exit;}
if(isset($_GET["delete_menu"])){$id=(int)$_GET["delete_menu"];$conn->query("UPDATE menu SET status=0 WHERE id=$id");header("Location: admin.php");exit;}
if(isset($_POST["update_menu"])){$id=(int)$_POST["id"];$nama=trim($_POST["nama"]);$harga=(int)$_POST["harga"];$kat=trim($_POST["kategori"]);$st=$conn->prepare("UPDATE menu SET nama=?,harga=?,kategori=? WHERE id=?");$st->bind_param("sisi",$nama,$harga,$kat,$id);$st->execute();header("Location: admin.php?ok=update");exit;}
$menuCount=$conn->query("SELECT COUNT(*) c FROM menu WHERE status=1")->fetch_assoc()["c"];
$userCount=$conn->query("SELECT COUNT(*) c FROM users WHERE role='user'")->fetch_assoc()["c"];
$trxCount=$conn->query("SELECT COUNT(*) c FROM transaksi")->fetch_assoc()["c"];
$sales=$conn->query("SELECT COALESCE(SUM(total),0) t FROM transaksi WHERE DATE(created_at)=CURDATE()")->fetch_assoc()["t"];
$menus=$conn->query("SELECT * FROM menu WHERE status=1 ORDER BY id DESC");
$tr=$conn->query("SELECT t.*,u.nama user_nama FROM transaksi t LEFT JOIN users u ON u.id=t.user_id ORDER BY t.id DESC LIMIT 50");
require "header.php";
?>
<section class="section admin-section"><div class="section-heading"><div><span class="eyebrow">ADMIN PANEL</span><h2>Dashboard Dapoer Omom</h2></div><a class="btn btn-primary" href="export.php">↗ Export Excel</a></div>
<div class="stats"><div><span>Penjualan Hari Ini</span><b><?=rupiah($sales)?></b></div><div><span>Menu Aktif</span><b><?=$menuCount?></b></div><div><span>Total User</span><b><?=$userCount?></b></div><div><span>Total Transaksi</span><b><?=$trxCount?></b></div></div>
<div class="admin-grid"><div class="card"><span class="mini-label">KELOLA MENU</span><h3>Tambah Menu</h3><form method="post"><input type="hidden" name="add_menu" value="1"><label>Nama Menu<input name="nama" required></label><label>Harga<input type="number" name="harga" required></label><label>Kategori<input name="kategori" value="MENU FAVORIT"></label><button class="btn btn-primary full">+ Tambah Menu</button></form></div>
<div class="card"><span class="mini-label">MENU AKTIF</span><h3>Daftar Menu</h3><?php while($m=$menus->fetch_assoc()):?><div class="admin-menu-row"><div><b><?=e($m["nama"])?></b><small><?=rupiah($m["harga"])?> • <?=e($m["kategori"])?></small></div><div><button type="button" class="mini-btn" onclick='editMenu(<?=json_encode($m,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Edit</button><a class="mini-btn danger" href="?delete_menu=<?=$m["id"]?>" onclick="return confirm('Nonaktifkan menu ini?')">Hapus</a></div></div><?php endwhile;?></div></div>
<div id="editBox" class="card edit-box" style="display:none"><span class="mini-label">EDIT MENU</span><h3>Ubah Data Menu</h3><form method="post"><input type="hidden" name="update_menu" value="1"><input type="hidden" id="editId" name="id"><label>Nama<input id="editNama" name="nama" required></label><label>Harga<input id="editHarga" type="number" name="harga" required></label><label>Kategori<input id="editKategori" name="kategori"></label><button class="btn btn-primary">Simpan Perubahan</button> <button type="button" class="btn btn-light" onclick="document.getElementById('editBox').style.display='none'">Batal</button></form></div>
<div class="card table-wrap"><div class="panel-title"><div><span class="mini-label">TRANSAKSI</span><h3>Riwayat Penjualan</h3></div><a class="btn btn-outline" href="export.php">Export</a></div><table><thead><tr><th>Kode</th><th>Pelanggan</th><th>User</th><th>Metode</th><th>Total</th><th>Waktu</th></tr></thead><tbody><?php while($r=$tr->fetch_assoc()):?><tr><td><?=e($r["kode"])?></td><td><?=e($r["pelanggan"])?></td><td><?=e($r["user_nama"]??"-")?></td><td><?=e($r["metode"])?></td><td><?=rupiah($r["total"])?></td><td><?=e($r["created_at"])?></td></tr><?php endwhile;?></tbody></table></div></section>
<script>
function editMenu(m){document.getElementById('editBox').style.display='block';document.getElementById('editId').value=m.id;document.getElementById('editNama').value=m.nama;document.getElementById('editHarga').value=m.harga;document.getElementById('editKategori').value=m.kategori;document.getElementById('editBox').scrollIntoView({behavior:'smooth'});}
</script>
<?php require "footer.php"; ?>